### ISSUE TITLE
Quiz 6 of week 1

### ISSUE THREAD

**Issue by Et9797** [goodhamgupta/maths-for-ml#1]
Hi, I have noticed the quizz answers from quiz 6 in week 6 don't show up in the pdf. Would you be so kind to take a screenshot of these so I can check my answers? Only if you have the time ofcourse! Thanks thus far!

**Comment by goodhamgupta** [comment]
Hi Et9797,

Unfortunately, my course subscription has ended a few months back. Due to this, I will not be able to access the quiz content. Please feel free to contribute your solutions here! 😄 

Thanks!
