### ISSUE TITLE
Hi there - Is it possible to see the solutions for Quiz 6, week 1 (calculus)>

### ISSUE THREAD

**Issue by Likemindprojects** [goodhamgupta/maths-for-ml#2]
Hi there, 

First up - just wanted to say many thanks for your solutions to the quiz's (they have saved me hours or work).

With regard to quiz 6 (week 1) is it possible to see the solutions? Currently, there's it's only showing you, your score.

Many thanks!

**Comment by goodhamgupta** [comment]
Hi @Likemindprojects ,

Thanks for your kind words! 😄 I've added the solutions for quiz 6 today. My solutions/notes can be improved a lot, so please do not hesitate to contribute to them. 

Thanks!

**Comment by Likemindprojects** [comment]
Thanks Shubham!
