### ISSUE TITLE
What is @ stands for

### ISSUE THREAD

**Issue by varunprepo** [goodhamgupta/maths-for-ml#3]
r = L @ r # Apply matrix L to r

**Comment by goodhamgupta** [comment]
Hi @coderYoyo ,

`@` signifies the dot product between the two vectors `L` and `r`.

**Comment by varunprepo** [comment]
> Hi @coderYoyo ,
> 
> `@` signifies the dot product between the two vectors `L` and `r`.
Please tell from where I can get this library from readonly.PageRankFunctions import * ?
If I skip the above line and execute the next steps I am not getting the correct answers.
Please help. dot product of L.r is also not giving the correct answers.
I am expecting the same answer. However, when I write L.r and run the program the results are not correct.

**Comment by goodhamgupta** [comment]
Hi @coderYoyo ,

Are you trying to run the notebooks locally? As far as I can remember, I don't think you'll be able to run the notebooks locally. The function you are talking about is only present on the Coursera servers, and they will be available to you when launch the notebook server from Coursera.

**Comment by varunprepo** [comment]
Yes you are right. I am trying to run the code locally. Thanks for replying to my query.

**Comment by goodhamgupta** [comment]
No problem! Please feel free to open up another issue in-case you're facing some other problems. Thanks!
